# Generated by Django 5.0.6 on 2024-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان درurl')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('link', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('logo', models.ImageField(upload_to='images/site-logo/', verbose_name='لوگو')),
                ('copy_right', models.CharField(max_length=500, verbose_name='متن کپی رایت')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('call_number', models.IntegerField(verbose_name='شماره تماس')),
                ('fax', models.IntegerField(verbose_name='فکس')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی ؟')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/slider/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
